import Header from "@/components/Header/Header"
import "../styles/./globals.css"
import Footer from "@/components/Footer/Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col min-h-screen">
          {/* <Header /> */}
          {children}
        </main>
      </body>
    </html>
  )
}
